import { ArrowRight, Flower2, Play, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { Lang } from '@/lib/game';
const copy = { en: { eyebrow: 'A Tamil village game, carried forward', title: 'Gather around.\nLet the seeds speak.', intro: 'Pazhakuzhi is the pocket-sized courtyard where generations meet. A warm, thoughtful game of rhythm, memory, and a little mischief.', play: 'Start a game', how: 'Learn the old way', note: 'No accounts. No noise. Just your turn.' }, ta: { eyebrow: 'தமிழ் மண்ணின் விளையாட்டு', title: 'சுற்றி அமருங்கள்.\nவிதைகள் பேசட்டும்.', intro: 'பழக்குழி என்பது தலைமுறைகள் சந்திக்கும் ஒரு சிறிய முற்றம். நினைவும், நிதானமும், கொஞ்சம் குறும்பும் கலந்த விளையாட்டு.', play: 'விளையாட்டைத் தொடங்கு', how: 'விதியை அறிக', note: 'கணக்கு இல்லை. சத்தம் இல்லை. உங்கள் முறை மட்டும்.' } };
export default function Home({ lang }: { lang: Lang }) {
  const c = copy[lang];
  return <div className="mx-auto max-w-7xl px-5 pb-12 pt-10 lg:px-9 lg:pt-16">
    <section className="grid items-center gap-10 lg:grid-cols-[1.02fr_.98fr] lg:gap-16">
      <div className="fade-up max-w-xl"><div className="mb-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-[#9b522f]"><Sparkles size={15}/>{c.eyebrow}</div><h1 className="display whitespace-pre-line text-5xl leading-[.98] text-[#3d2417] sm:text-7xl">{c.title}</h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#6b5142]">{c.intro}</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/setup" data-testid="link-start-game" className="inline-flex items-center gap-3 rounded-full bg-[#a84e2d] px-6 py-3.5 font-semibold text-[#fff5e5] shadow-[0_8px_0_#7c3823] transition hover:-translate-y-0.5 hover:shadow-[0_10px_0_#7c3823] active:translate-y-1 active:shadow-[0_3px_0_#7c3823]">{c.play}<ArrowRight size={18}/></Link><Link href="/how-to-play" data-testid="link-how-to-play" className="inline-flex items-center gap-2 rounded-full px-5 py-3 font-semibold text-[#205c5a] hover:bg-[#e6d1a8]"><BookIcon/>{c.how}</Link></div><p className="mt-5 text-xs text-[#967e6c]">{c.note}</p></div>
      <div className="fade-up relative [animation-delay:120ms]"><div className="absolute -left-5 -top-6 h-24 w-24 rounded-full border border-dashed border-[#c48752] opacity-60"/><div className="relative mx-auto max-w-[570px] rotate-1 rounded-[2.5rem] border-[12px] border-[#6c3822] p-5 wood"><div className="rounded-[1.75rem] border border-[#e8bd78]/40 bg-[#87502d]/50 p-4"><div className="mb-3 flex items-center justify-between px-2 text-[#f3d9a7]"><span className="tamil text-sm">பழக்குழி</span><span className="text-[10px] uppercase tracking-[.2em] opacity-70">PALLANKUZHI</span></div><div className="grid grid-cols-7 gap-2.5 rounded-[1.5rem] bg-[#542d1c]/55 p-3">{Array.from({ length: 14 }, (_, i) => <div key={i} className="pit flex aspect-square items-center justify-center rounded-full border border-[#d6a264]/20">{Array.from({ length: [5,3,6,4,7,2,5,4,6,3,5,7,2,4][i] }, (_, j) => <i key={j} className="seed"/>)}</div>)}</div><div className="mt-4 flex justify-between px-3 text-[10px] uppercase tracking-[.18em] text-[#f0d2a2]/70"><span>Your side</span><span>Take a breath · take a turn</span></div></div></div><div className="absolute -bottom-7 -right-3 flex h-20 w-20 items-center justify-center rounded-full border-8 border-[#e8c78f] bg-[#205c5a] text-[#f3d9a7] shadow-lg"><Flower2 size={30}/></div></div>
    </section>
    <section className="mt-24 grid gap-6 border-y border-[#d7bb94] py-8 md:grid-cols-3"><div className="flex gap-4"><span className="text-3xl text-[#a84e2d]">01</span><div><h2 className="display text-xl">A game with a pulse</h2><p className="mt-1 text-sm leading-6 text-[#725c4c]">Sow one seed at a time. Listen to the board. Find the rhythm.</p></div></div><div className="flex gap-4"><span className="text-3xl text-[#a84e2d]">02</span><div><h2 className="display text-xl">For every generation</h2><p className="mt-1 text-sm leading-6 text-[#725c4c]">Play the computer, a sibling, or the person beside you.</p></div></div><div className="flex gap-4"><span className="text-3xl text-[#a84e2d]">03</span><div><h2 className="display text-xl tamil">பழமை புதுமை</h2><p className="mt-1 text-sm leading-6 text-[#725c4c]">A familiar board, made gentle for today’s screens.</p></div></div></section>
    <section className="mt-16 flex flex-col justify-between gap-6 rounded-[2rem] bg-[#205c5a] px-7 py-9 text-[#f7e8ca] sm:flex-row sm:items-center sm:px-12"><div><p className="tamil text-sm text-[#f0c987]">நம் பாரம்பரியம் – நம் விளையாட்டு</p><h2 className="display mt-2 text-3xl">Keep a little courtyard close.</h2></div><Link href="/about" data-testid="link-about-story" className="inline-flex items-center gap-2 self-start rounded-full border border-[#d8b477]/50 px-5 py-3 text-sm font-semibold hover:bg-[#2b706d]">Read the story <ArrowRight size={16}/></Link></section>
  </div>;
}
function BookIcon() { return <span className="inline-flex h-5 w-5 items-center justify-center rounded border border-[#205c5a] text-[10px]">?</span>; }