import { ArrowRight, BookOpen, Check, ChevronDown, Leaf, Quote, Sprout, Star } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'wouter';
import { Lang, loadStats } from '@/lib/game';

export default function HowToPlay({ lang }: { lang: Lang }) {
  const [open, setOpen] = useState(0);
  const items = lang === 'ta' ? [
    ['ஒரு குழியைத் தேர்ந்தெடு', 'உங்கள் பக்கத்தில் விதைகள் இருக்கும் குழியைத் தட்டவும். அந்த விதைகள் உங்கள் கையில் வரும்.'],
    ['ஒன்றாக விதை', 'வலப்பக்கம் நோக்கி ஒவ்வொரு குழியிலும் ஒரு விதை வீதம் போடவும். கடைசி விதை விழும் இடம்தான் அடுத்தக் குறிப்பு.'],
    ['பிடித்துக் கொள்', 'மரபு விதியில், கடைசி விதை எதிர் பக்கத்தில் இரண்டாகவோ அதற்கு மேலாகவோ இருந்தால் அவற்றை எடுத்துக் கொள்ளலாம்.'],
    ['யார் வென்றார்?', 'ஒரு பக்கத்தின் குழிகள் காலியானதும் ஆட்டம் முடியும். அதிக விதைகளைச் சேர்த்தவர் வெற்றி.'],
  ] : [
    ['Choose a pit', 'Tap any pit on your side with seeds in it. Those seeds come into your hand.'],
    ['Sow one by one', 'Move clockwise, dropping one seed in every pit. Where the last seed lands is your next clue.'],
    ['Capture the moment', 'In classic play, if the last seed lands in an opposing pit holding two or more, gather them home.'],
    ['Find the keeper', 'When one side is empty, the round ends. The player who gathered more seeds wins.'],
  ];
  return <div className="mx-auto max-w-5xl px-5 py-10 lg:px-9 lg:py-16"><div className="grid gap-12 lg:grid-cols-[.82fr_1.18fr]"><div><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#a84e2d]"><BookOpen size={15}/> THE QUIET RULES</p><h1 className="display text-5xl leading-tight text-[#3d2417]">{lang === 'ta' ? 'விதையைத் தொடங்கு.' : 'Start with a seed.'}</h1><p className="mt-5 leading-7 text-[#725c4c]">{lang === 'ta' ? 'இந்த விளையாட்டைக் கற்க ஒரு முழு பிற்பகல் தேவையில்லை. முதல் சுற்றிலேயே பலகை சொல்லித் தரும்.' : 'You do not need an afternoon to learn this game. The board teaches you before the first round is through.'}</p><Link href="/setup" data-testid="link-tutorial-start" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#205c5a] px-5 py-3 font-semibold text-[#f7e8ca]">Try a round <ArrowRight size={17}/></Link></div><div className="space-y-3">{items.map(([title, body], i) => <div key={title} className={`rounded-2xl border ${open === i ? 'border-[#c4864f] bg-[#f0d09d]' : 'border-[#d7bb94] bg-[#f7e8ca]/60'}`}><button onClick={() => setOpen(open === i ? -1 : i)} data-testid={`button-rule-${i}`} className="flex w-full items-center gap-4 p-5 text-left"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#a84e2d] font-bold text-[#fff5e5]">{open === i ? <Check size={16}/> : `0${i + 1}`}</span><span className="flex-1 font-bold">{title}</span><ChevronDown size={18} className={open === i ? 'rotate-180 transition' : 'transition'}/></button>{open === i && <p className="fade-up px-5 pb-5 pl-[4.5rem] text-sm leading-6 text-[#694d3c]">{body}</p>}</div>)}</div></div><div className="mt-20 grid items-center gap-8 rounded-[2rem] bg-[#205c5a] p-8 text-[#f7e8ca] md:grid-cols-[1fr_auto] md:p-12"><div><p className="tamil text-sm text-[#f0c987]">பலகை ஒரு ஆசிரியர்</p><h2 className="display mt-2 text-3xl">Slow hands see more.</h2><p className="mt-3 max-w-xl leading-7 text-[#d8dfcf]">There is no rush in a good game of Pazhakuzhi. Count carefully. Notice the quiet pit. Keep one seed back for the turn you cannot see yet.</p></div><div className="hidden h-28 w-28 rounded-full border border-[#e3bc79]/70 md:block"><div className="m-7 h-12 w-12 rounded-full border border-dashed border-[#e3bc79]"/></div></div></div>;
}

export function About({ lang }: { lang: Lang }) { return <div className="mx-auto max-w-5xl px-5 py-10 lg:px-9 lg:py-16"><div className="max-w-2xl"><p className="tamil text-sm font-semibold text-[#a84e2d]">நம் பாரம்பரியம் – நம் விளையாட்டு</p><h1 className="display mt-3 text-5xl leading-tight text-[#3d2417]">{lang === 'ta' ? 'ஒரு மரப்பலகையின் நினைவு.' : 'A memory, shaped like wood.'}</h1><p className="mt-6 text-lg leading-8 text-[#725c4c]">{lang === 'ta' ? 'பழக்குழி என்பது வெற்றி மட்டும் அல்ல. அது அருகில் அமர்ந்து, கைகளைப் பார்த்து, கதைகளைப் பகிர்ந்து கொள்ளும் நேரம்.' : 'Pazhakuzhi is not only about winning. It is the time spent sitting close, watching hands, and passing stories across a board.'}</p></div><div className="mt-16 grid gap-5 md:grid-cols-3"><Story icon={<Leaf/>} title={lang === 'ta' ? 'முற்றத்தில்' : 'In the courtyard'} body={lang === 'ta' ? 'மாலை காற்று, கோலத்தின் கோடுகள், விதைகளின் சிறு சத்தம்.' : 'An evening breeze, kolam lines, and the tiny sound of seeds finding wood.'}/><Story icon={<Sprout/>} title={lang === 'ta' ? 'தலைமுறைகள்' : 'Across generations'} body={lang === 'ta' ? 'ஒரு பாட்டியின் விதி, ஒரு குழந்தையின் புதிய தந்திரம்.' : 'A grandmother’s rule. A child’s new trick. Both belong at the table.'}/><Story icon={<Star/>} title={lang === 'ta' ? 'இன்றைக்கு' : 'For today'} body={lang === 'ta' ? 'அதே வெப்பம், இப்போது எங்கு வேண்டுமானாலும்.' : 'The same warmth, now wherever a screen can make room for two.'}/></div><div className="mt-16 border-y border-[#d7bb94] py-10 text-center"><Quote className="mx-auto text-[#a84e2d]" size={28}/><p className="display mx-auto mt-4 max-w-2xl text-3xl leading-snug text-[#3d2417]">{lang === 'ta' ? 'விளையாட்டு முடிந்தாலும், கதை தொடர்கிறது.' : 'The game ends. The story keeps going.'}</p></div></div>; }
function Story({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="rounded-2xl border border-[#d7bb94] bg-[#f7e8ca]/70 p-6"><div className="mb-7 inline-flex rounded-full bg-[#f0d09d] p-3 text-[#a84e2d]">{icon}</div><h2 className="display text-2xl">{title}</h2><p className="mt-3 text-sm leading-6 text-[#725c4c]">{body}</p></div>; }

export function Stats({ lang }: { lang: Lang }) { const s = loadStats(); return <div className="mx-auto max-w-5xl px-5 py-10 lg:px-9 lg:py-16"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a84e2d]">YOUR KEEPSAKE · உங்கள் பதிவு</p><h1 className="display mt-3 text-5xl text-[#3d2417]">{lang === 'ta' ? 'ஆட்டங்களின் தடம்.' : 'A trail of games.'}</h1><p className="mt-4 max-w-lg text-[#725c4c]">{lang === 'ta' ? 'ஒவ்வொரு சுற்றும் ஒரு சிறிய நினைவு. இங்கே உங்கள் பயணம்.' : 'Every round leaves a little mark. Here is yours so far.'}</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label={lang === 'ta' ? 'ஆட்டங்கள்' : 'Games played'} value={s.games}/><Stat label={lang === 'ta' ? 'வெற்றிகள்' : 'Rounds won'} value={s.wins}/><Stat label={lang === 'ta' ? 'சிறந்த சுற்று' : 'Longest round'} value={s.best}/><Stat label={lang === 'ta' ? 'பிடித்த விதைகள்' : 'Seeds gathered'} value={s.seeds}/></div><div className="mt-12 rounded-[2rem] bg-[#205c5a] p-8 text-[#f7e8ca] md:p-10"><h2 className="display text-3xl">{lang === 'ta' ? 'அடுத்த முறை...' : 'Next time…'}</h2><p className="mt-3 max-w-lg leading-7 text-[#d8dfcf]">{s.games ? (lang === 'ta' ? 'உங்கள் கை நினைவில் வைத்திருக்கும். இன்னொரு சுற்று விளையாடுங்கள்.' : 'Your hands remember more than you think. Sit down for another round.') : (lang === 'ta' ? 'உங்கள் முதல் விதை இன்னும் காத்திருக்கிறது.' : 'Your first seed is still waiting to be sown.')}</p><Link href="/setup" data-testid="link-stats-new-game" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#f0c987] px-5 py-3 font-semibold text-[#3d2417]">Begin a game <ArrowRight size={16}/></Link></div></div>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-[#d7bb94] bg-[#f7e8ca]/70 p-5"><span className="display text-4xl text-[#a84e2d]">{value}</span><p className="mt-2 text-sm text-[#725c4c]">{label}</p></div>; }