import { ArrowLeft, CirclePause, CirclePlay, Flag, History, RotateCcw, Timer, Trophy } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { createGame, formatDuration, GameState, Lang, legalPits, loadGame, loadStats, saveGame, saveStats, sow } from '@/lib/game';

const strings = { en: { yourTurn: 'Your turn', otherTurn: 'Computer is thinking', playerTwo: 'Player 2’s turn', choose: 'Choose a pit to begin sowing', captured: 'captured', moves: 'moves', pause: 'Pause', resume: 'Resume', exit: 'Exit game', restart: 'Restart', history: 'Move history', result: 'Round complete', win: 'wins the round', draw: 'A beautiful draw', again: 'Play again', new: 'New game', home: 'Home' }, ta: { yourTurn: 'உங்கள் முறை', otherTurn: 'கணினி யோசிக்கிறது', playerTwo: 'வீரர் 2-ன் முறை', choose: 'விதை விதைக்க ஒரு குழியைத் தேர்ந்தெடுக்கவும்', captured: 'பிடித்தவை', moves: 'நகர்வுகள்', pause: 'இடைநிறுத்து', resume: 'தொடரு', exit: 'வெளியேறு', restart: 'மீண்டும் தொடங்கு', history: 'நகர்வு வரலாறு', result: 'சுற்று முடிந்தது', win: 'சுற்றில் வெற்றி', draw: 'அழகான சமநிலை', again: 'மீண்டும் விளையாடு', new: 'புதிய ஆட்டம்', home: 'முகப்பு' } };

export default function Play({ lang, sound }: { lang: Lang; sound: boolean }) {
  const t = strings[lang]; const [, setLocation] = useLocation(); const [game, setGame] = useState<GameState>(() => loadGame() || createGame()); const [elapsed, setElapsed] = useState(0); const [showHistory, setShowHistory] = useState(false);
  useEffect(() => { if (!game || game.paused || game.finished) return; const i = window.setInterval(() => setElapsed(Date.now() - game.startedAt), 1000); return () => window.clearInterval(i); }, [game?.paused, game?.finished, game?.startedAt]);
  useEffect(() => { if (!game || game.finished || game.paused || game.settings.mode !== 'computer' || game.turn !== 1) return; const delay = window.setTimeout(() => { const picks = legalPits(game); if (picks.length) commit(sow(game, picks[game.moves.length % picks.length])); }, game.settings.difficulty === 'easy' ? 400 : game.settings.difficulty === 'hard' ? 900 : 650); return () => window.clearTimeout(delay); }, [game]);
  const commit = (next: GameState) => { setGame(next); saveGame(next); if (next.finished) { const old = loadStats(); saveStats({ games: old.games + 1, wins: old.wins + (next.winner === 0 ? 1 : 0), best: Math.max(old.best, next.moves.length), seeds: old.seeds + next.captured[0] }); } };
  const currentPits = game.pits.slice(0, game.settings.pits); const opposingPits = game.pits.slice(game.settings.pits).reverse(); const legal = useMemo(() => legalPits(game), [game]); const humanTurn = game.settings.mode === 'local' || game.turn === 0;
  const reset = () => { const next = createGame(game.settings); commit(next); setElapsed(0); };
  const exit = () => { saveGame(null); setLocation('/'); };
  const selectPit = (index: number) => { if (humanTurn) commit(sow(game, index)); };
  return <div className="mx-auto max-w-7xl px-4 py-7 lg:px-9 lg:py-10">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a84e2d]">PAZHAKUZHI · {game.settings.pits} PITS</p><h1 className="display mt-1 text-3xl text-[#3d2417]">{game.finished ? t.result : game.turn === 0 ? t.yourTurn : game.settings.mode === 'computer' ? t.otherTurn : t.playerTwo}</h1></div><div className="flex items-center gap-2"><span className="flex items-center gap-1.5 rounded-full border border-[#d7bb94] bg-[#f7e8ca] px-3 py-2 text-xs font-semibold"><Timer size={14}/>{formatDuration(elapsed)}</span><button onClick={() => setShowHistory(!showHistory)} data-testid="button-show-history" className="rounded-full border border-[#d7bb94] bg-[#f7e8ca] p-2.5" aria-label={t.history}><History size={17}/></button><button onClick={() => { const next = { ...game, paused: !game.paused }; setGame(next); saveGame(next); }} data-testid="button-pause-game" className="flex items-center gap-2 rounded-full border border-[#d7bb94] bg-[#f7e8ca] px-3 py-2 text-xs font-semibold">{game.paused ? <CirclePlay size={16}/> : <CirclePause size={16}/>} {game.paused ? t.resume : t.pause}</button><button onClick={exit} data-testid="button-exit-game" className="rounded-full border border-[#d7bb94] p-2.5 text-[#a84e2d]" aria-label={t.exit}><ArrowLeft size={17}/></button></div></div>
    {game.finished ? <Result game={game} lang={lang} onAgain={reset} onNew={() => setLocation('/setup')} onHome={exit}/> : <><div className="mb-5 flex items-center justify-between rounded-2xl border border-[#d7bb94] bg-[#f7e8ca]/80 px-4 py-3 text-sm"><span className={game.turn === 0 ? 'font-bold text-[#a84e2d]' : 'text-[#725c4c]'}>● {lang === 'ta' ? 'நீங்கள்' : 'You'}</span><span className="text-xs text-[#967e6c]">{t.choose}</span><span className={game.turn === 1 ? 'font-bold text-[#205c5a]' : 'text-[#725c4c]'}>● {game.settings.mode === 'computer' ? 'Pazhaiya Paati' : lang === 'ta' ? 'வீரர் 2' : 'Player 2'}</span></div><div className="relative mx-auto max-w-5xl rounded-[2rem] border-[10px] border-[#6c3822] p-4 shadow-[0_25px_50px_rgba(76,43,23,.2)] wood sm:p-7"><div className="relative rounded-[1.25rem] border border-[#e5b976]/40 bg-[#87502d]/60 p-3 sm:p-5"><div className="mb-4 flex items-center justify-between px-2 text-[#f0d2a2]"><span className="tamil text-sm">பழக்குழி</span><span className="text-[10px] uppercase tracking-[.2em] opacity-70">SOW · COUNT · CAPTURE</span></div><BoardRow pits={opposingPits} offset={game.settings.pits} legal={[]} onSelect={selectPit} flipped/><div className="my-4 flex items-center justify-between gap-3 border-y border-[#d8a96d]/30 py-3 text-[#f0d2a2]"><Capture count={game.captured[1]} label={game.settings.mode === 'computer' ? 'Pazhaiya Paati' : 'Player 2'} /><div className="h-px flex-1 bg-[#e5b976]/30"/><Capture count={game.captured[0]} label={lang === 'ta' ? 'நீங்கள்' : 'You'} /></div><BoardRow pits={currentPits} offset={0} legal={legal} onSelect={selectPit}/></div></div><p className="mt-5 text-center text-sm text-[#725c4c]">{game.paused ? (lang === 'ta' ? 'ஆட்டம் இடைநிறுத்தப்பட்டுள்ளது' : 'The board is resting') : game.turn === 0 ? t.choose : t.otherTurn}</p></>}
    {showHistory && <aside className="fixed right-4 top-24 z-10 w-72 rounded-2xl border border-[#d7bb94] bg-[#fff5e5] p-5 shadow-[var(--shadow-card)]"><div className="flex items-center justify-between"><h2 className="display text-xl">{t.history}</h2><button onClick={() => setShowHistory(false)} className="text-xl" aria-label="Close history">×</button></div><div className="mt-4 max-h-72 space-y-2 overflow-auto text-sm">{game.moves.length ? game.moves.slice().reverse().map((m, i) => <div key={`${m.player}-${i}`} data-testid={`history-move-${i}`} className="flex justify-between border-b border-[#ead8bb] pb-2"><span>{m.player === 0 ? 'You' : 'Paati'} · pit {m.pit + 1}</span><b>+{m.captured}</b></div>) : <p className="text-[#967e6c]">Your first move is waiting.</p>}</div></aside>}
  </div>;
}
function BoardRow({ pits, offset, legal, onSelect, flipped = false }: { pits: number[]; offset: number; legal: number[]; onSelect: (i: number) => void; flipped?: boolean }) { return <div className={`grid grid-cols-5 gap-2.5 sm:grid-cols-7 sm:gap-3 ${flipped ? 'opacity-95' : ''}`}>{pits.map((count, i) => <button key={i} disabled={!legal.includes(offset + i)} onClick={() => onSelect(offset + i)} data-testid={`button-pit-${offset + i}`} aria-label={`Pit ${i + 1}, ${count} seeds`} className={`pit relative flex aspect-square min-h-[54px] items-center justify-center rounded-full border border-[#d6a264]/20 transition sm:min-h-[78px] ${legal.includes(offset + i) ? 'cursor-pointer ring-2 ring-[#f0c987] ring-offset-2 ring-offset-[#754126] hover:scale-105' : 'cursor-default'} ${flipped ? 'rotate-180' : ''}`}><span className="flex max-w-[44px] flex-wrap justify-center gap-0.5">{Array.from({ length: Math.min(count, 18) }, (_, j) => <i className="seed" key={j}/>)}</span><span className="absolute bottom-1 text-[9px] font-bold text-[#f4d39f]/75">{count}</span></button>)}</div>; }
function Capture({ count, label }: { count: number; label: string }) { return <div className="flex min-w-[72px] items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-full border border-[#dfb675] bg-[#542d1c] text-sm font-bold text-[#f0c987]">{count}</div><span className="text-[10px] uppercase tracking-wider">{label}</span></div>; }
function Result({ game, lang, onAgain, onNew, onHome }: { game: GameState; lang: Lang; onAgain: () => void; onNew: () => void; onHome: () => void }) { const t = strings[lang]; const winner = game.winner === 0 ? (lang === 'ta' ? 'நீங்கள்' : 'You') : game.settings.mode === 'computer' ? 'Pazhaiya Paati' : lang === 'ta' ? 'வீரர் 2' : 'Player 2'; return <div className="mx-auto max-w-3xl rounded-[2rem] border border-[#d7bb94] bg-[#f7e8ca] p-6 text-center shadow-[var(--shadow-card)] sm:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#205c5a] text-[#f0c987]"><Trophy size={30}/></div><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-[#a84e2d]">{t.result}</p><h2 className="display mt-2 text-5xl text-[#3d2417]">{winner} <span className="text-3xl">{t.win}</span></h2><div className="my-9 grid grid-cols-3 divide-x divide-[#d7bb94]"><div><b className="display text-3xl">{game.captured[0]}</b><p className="text-xs">{lang === 'ta' ? 'நீங்கள் பிடித்தவை' : 'Your seeds'}</p></div><div><b className="display text-3xl">{game.moves.length}</b><p className="text-xs">{t.moves}</p></div><div><b className="display text-3xl">{game.captured[1]}</b><p className="text-xs">{lang === 'ta' ? 'எதிரியின் விதைகள்' : 'Other seeds'}</p></div></div><div className="flex flex-wrap justify-center gap-3"><button onClick={onAgain} data-testid="button-play-again" className="flex items-center gap-2 rounded-xl bg-[#a84e2d] px-5 py-3 font-bold text-[#fff5e5]"><RotateCcw size={17}/>{t.again}</button><button onClick={onNew} data-testid="button-new-game" className="rounded-xl border border-[#cda77b] px-5 py-3 font-semibold">{t.new}</button><button onClick={onHome} data-testid="button-result-home" className="rounded-xl border border-[#cda77b] px-5 py-3 font-semibold">{t.home}</button></div></div>; }